export const SonarqubeActionType = {
    QUALITY: 'SONARQUBE_ACTION.QUALITY',
    LOC: 'SONARQUBE_ACTION.LOC',
    COVERAGE: 'SONARQUBE_ACTION.COVERAGE',
    DUPLICATION: 'SONARQUBE_ACTION.DUPLICATION'
};

